server:
  port: 8888
spring:
  application:
    name: ms-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos.host
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api-user/**
logging:
  file:
    path: /var/logs/ms-platform/